# Generated by Django 3.2.1 on 2023-05-13 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_userprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
