# Generated by Django 3.2.1 on 2023-05-13 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='comment',
            table='home_cmt',
        ),
    ]
