# Generated by Django 3.2.1 on 2023-05-13 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20230513_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='id_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.homemypost'),
            preserve_default=False,
        ),
    ]
