# Generated by Django 3.2.1 on 2023-05-13 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_comment_id_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='id_post',
            new_name='post',
        ),
    ]
