# Generated by Django 3.2.1 on 2023-05-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_review_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
