# Generated by Django 3.2.1 on 2023-05-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='list_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='homemypost',
            name='images',
        ),
        migrations.AddField(
            model_name='homemypost',
            name='images',
            field=models.ManyToManyField(blank=True, to='home.Image'),
        ),
    ]
