# Generated by Django 3.2.1 on 2023-05-27 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20230527_1218'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ListImage',
        ),
        migrations.RenameField(
            model_name='listimage',
            old_name='image',
            new_name='listimage',
        ),
    ]
