# Generated by Django 3.2.1 on 2023-05-28 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20230527_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='price',
            field=models.TextField(blank=True, null=True),
        ),
    ]
