# Generated by Django 3.2.1 on 2023-05-28 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_userprofile_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='price',
        ),
    ]
