# Generated by Django 3.2.1 on 2023-05-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_userprofile_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_host',
            field=models.IntegerField(default=0),
        ),
    ]
