# Generated by Django 3.2.1 on 2023-05-30 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_homemypost_fblink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homemypost',
            name='fblink',
        ),
    ]
