# Generated by Django 3.2.1 on 2023-05-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_userprofile_fblink'),
    ]

    operations = [
        migrations.AddField(
            model_name='homemypost',
            name='addressdetail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
