# Generated by Django 3.2.1 on 2023-05-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_homemypost_addressdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='homemypost',
            name='chieudai',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homemypost',
            name='chieurong',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homemypost',
            name='dientich',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homemypost',
            name='mattien',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homemypost',
            name='solau',
            field=models.TextField(blank=True, null=True),
        ),
    ]
