# Generated by Django 3.2.1 on 2023-06-05 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20230530_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='homemypost',
            name='duongtruocnha',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homemypost',
            name='guess_price',
            field=models.TextField(blank=True, null=True),
        ),
    ]
