# Generated by Django 3.2.1 on 2023-06-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20230605_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='homemypost',
            name='dochinhxac',
            field=models.TextField(blank=True, null=True),
        ),
    ]
