# Generated by Django 3.2.1 on 2023-06-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_homemypost_dochinhxac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homemypost',
            name='bathroom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homemypost',
            name='bedroom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homemypost',
            name='guess_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homemypost',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homemypost',
            name='solau',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
